debug=false
# DAVELOPPEMENT
#server.port=8080
#spring.profiles.active=dev
# PRODUCTION
server.port=80
spring.profiles.active=prod
spring.mvc.favicon.enabled=false
server.servlet.session.timeout=30m
spring.devtools.add-properties=false

server.tomcat.compression=on
server.compression.enabled=true
server.compression.min-response-size=4096
server.compression.mime-types=text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
logging.level.org.apache.tiles=ERROR
logging.level.org.hibernate=ERROR
# SCHEDULE second minute hour dayOfMonth month daysOfweek
purge.cron.expression=0 0 5 * * ?
purge.cron.alert.post=0 0 7 * * ?
purge.cron.alert.ads=0 10 7 * * ?
purge.cron.alert.event=0 20 7 * * ?
purge.cron.alert.jobs=0 30 7 * * ?
# RECAPTCHA GOOGLE
google.recaptcha.key.site=6LeCT8waAAAAAMdj9QOU3tUNnSZe8YRLn9_c6wgG
google.recaptcha.key.secret=6LeCT8waAAAAAIOfc_jBVcHobumrcBjgu4VQS01Q
# I18N
spring.messages.encoding=UTF-8
spring.messages.basename=i18n/messages
# JPA / HIBERNATE
spring.jpa.show-sql=false
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.open-in-view=false
spring.jpa.properties.jadira.usertype.autoRegisterUserTypes=true
# DATABASE dev
#spring.datasource.url=jdbc:postgresql://localhost:5432/aobase?useUnicode=true&characterEncoding=UTF8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
#spring.datasource.username=redagres
#spring.datasource.password=Rplusads@87!M3i
# DATABASE prod
spring.datasource.url=jdbc:postgresql://algerieoffice-server.postgres.database.azure.com:5432/aobase?ssl=true&sslmode=require&useUnicode=true&characterEncoding=UTF8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
spring.datasource.username=algerieofficegres@algerieoffice-server
spring.datasource.password=Rplus@rinitec!87
spring.datasource.driver-class-name=org.postgresql.Driver
# MULTIPART FILE 2Mb
multipart.maxFileSize=2097152
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=10MB
# TWILIO SMS
twilio.account.sid=ACf1c9202d8d2979fcc47f5d2a0afccbb2
twilio.auth.token=7c0c1b3b0016e60e28c56b90fda7c2ca
twilio.phone.number=+15162104089
# SENDGRID
support.email=algerieoffice-mail
spring.mail.default-encoding=UTF-8
spring.mail.host=smtp.sendgrid.net
spring.mail.username=apikey
spring.mail.password=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
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.timeout=10000
# SOCIAL OAUTH2
spring.security.oauth2.client.registration.google.clientId=690267838782-3v4j1jvp7oaa1pd799iivijuqt4kki4q.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.clientSecret=zuubNDziDbhDIexPNe9m4VNo
spring.security.oauth2.client.registration.facebook.clientId=2623315594472108
spring.security.oauth2.client.registration.facebook.clientSecret=74fefcd0c16e0eff2e2c7b69692aec99
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email,picture
spring.security.oauth2.client.registration.linkedin.clientId=86s180we52h843
spring.security.oauth2.client.registration.linkedin.clientSecret=PpwHErJlsTABeYkZ
spring.security.oauth2.client.registration.linkedin.client-authentication-method=post
spring.security.oauth2.client.registration.linkedin.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.linkedin.scope=r_liteprofile, r_emailaddress
spring.security.oauth2.client.registration.linkedin.redirect-uri-template={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.linkedin.client-name=Linkedin
spring.security.oauth2.client.registration.linkedin.provider=linkedin
spring.security.oauth2.client.provider.linkedin.authorization-uri=https://www.linkedin.com/oauth/v2/authorization
spring.security.oauth2.client.provider.linkedin.token-uri=https://www.linkedin.com/oauth/v2/accessToken
spring.security.oauth2.client.provider.linkedin.user-info-uri=https://api.linkedin.com/v2/me
spring.security.oauth2.client.provider.linkedin.user-name-attribute=id
linkedin.email-address-uri=https://api.linkedin.com/v2/emailAddress?q=members&projection=(elements*(handle~))
# BEAN 2.1.8.RELEASE
spring.main.allow-bean-definition-overriding=true
# AZURE
azure.application.insights.instrumentation.key=2052061c-2556-4aa2-95d8-14a5dd582809
azure.storage.connection-string=DefaultEndpointsProtocol=https;AccountName=algerieofficestorage;AccountKey=zxlbYeF07tebGf1BeaoHOvpXtQesB2z52pOzW57iPcpW7JT48Q5hW+U9pMYtchnV8LeEqb+XuI/pjV/6TaWk6g==;EndpointSuffix=core.windows.net
#azure.storage.container-name=workspace
#spring.cloud.azure.credential-file-path=ao.azureauth
#spring.cloud.azure.resource-group=algerieoffice-groupe
#spring.cloud.azure.region=westeurope
#spring.cloud.azure.storage.account=algerieofficestorage